---
- name: "Configure Pfsense DHCP Static Mappings"
  become: yes
  hosts: all

  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11  # Adjust the path as needed
  
  tasks:
    - name: Create DHCP static mapping
      pfsensible.core.pfsense_dhcp_static:
        name: "{{ mapping_name }}"
        macaddr: "{{ mac_address }}"
        ipaddr: "{{ ip_address }}"
        state: present
      when: mapping_state == 'present'

    - name: Delete DHCP static mapping
      pfsensible.core.pfsense_dhcp_static:
        name: "{{ mapping_name }}"
        state: absent
      when: mapping_state == 'absent'
