---
- name: Configure DHCP Static Mappings
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Create or edit DHCP static mapping
      pfsensible.core.pfsense_dhcp_static:
        name: "{{ mapping_name }}"
        macaddr: "{{ mac_address }}"
        ipaddr: "{{ ip_address }}"
        state: "{{ mapping_state }}"
      when: 
        - mapping_state == 'present'  # Adding a new entry
        - edit is not defined         # Editing an existing entry
      
    - name: Delete DHCP static mapping
      pfsensible.core.pfsense_dhcp_static:
        name: "{{ mapping_name }}"
        state: absent
      when: mapping_state == 'absent'
