---
- name: Configure pfSense/OPNsense for KPN Internet with IPTV
  hosts: your_firewall_host
  gather_facts: no
  vars:
    wan_interface: "em0"  # Change this to your WAN interface name
    pppoe_username: "internet"
    pppoe_password: "internet"
    internet_vlan_id: "6"  # Change this to your Internet VLAN ID
    internet_interface: "em0.6"  # Change this to your Internet interface
    iptv_vlan_id: "4"  # Change this to your IPTV VLAN ID
    iptv_interface: "em0.4"  # Change this to your IPTV interface

  tasks:
    - name: Install required packages
      pkg:
        name: "curl"
        state: present

    - name: Set WAN interface to PPPoE
      command: >
        curl -X POST -d '{"if": "{{ wan_interface }}", "type": "pppoe", "username": "{{ pppoe_username }}", "password": "{{ pppoe_password }}", "descr": "KPN PPPoE"}'
        http://localhost/api/v1/interfaces

    - name: Set up Internet VLAN
      command: >
        curl -X POST -d '{"if": "{{ internet_interface }}", "tag": "{{ internet_vlan_id }}", "descr": "Internet"}'
        http://localhost/api/v1/interfaces/vlan

    - name: Set up IPTV VLAN
      command: >
        curl -X POST -d '{"if": "{{ iptv_interface }}", "tag": "{{ iptv_vlan_id }}", "descr": "IPTV"}'
        http://localhost/api/v1/interfaces/vlan

    - name: Configure Internet firewall rules
      command: >
        curl -X POST -d '{"type": "pass", "interface": "{{ internet_interface }}", "ipprotocol": "inet", "descr": "Allow Internet"}'
        http://localhost/api/v1/firewall/rules

    - name: Configure IPTV firewall rules
      command: >
        curl -X POST -d '{"type": "pass", "interface": "{{ iptv_interface }}", "ipprotocol": "inet", "protocol": "igmp", "descr": "Allow IGMP"}'
        http://localhost/api/v1/firewall/rules

    - name: Open SSH port for destination IP 192.168.2.2
      command: >
        curl -X POST -d '{"type": "pass", "interface": "{{ internet_interface }}", "ipprotocol": "inet", "protocol": "tcp", "source": "any", "sourceport": "", "destination": "192.168.2.2", "destinationport": "22", "descr": "Allow SSH to 192.168.2.2"}'
        http://localhost/api/v1/firewall/rules

    - name: Open HTTP and HTTPS ports for destination IP 1.2.3.4
      command: >
        curl -X POST -d '{"type": "pass", "interface": "{{ internet_interface }}", "ipprotocol": "inet", "protocol": "tcp", "source": "any", "sourceport": "", "destination": "1.2.3.4", "destinationport": "80", "descr": "Allow HTTP to 1.2.3.4"}'
        http://localhost/api/v1/firewall/rules

    - name: Configure HTTPS
      command: >
        curl -X POST -d '{"type": "pass", "interface": "{{ internet_interface }}", "ipprotocol": "inet", "protocol": "tcp", "source": "any", "sourceport": "", "destination": "1.2.3.4", "destinationport": "443", "descr": "Allow HTTPS to 1.2.3.4"}'
        http://localhost/api/v1/firewall/rules

    - name: Open SMTP (25) and Submission (587) ports for destination IP 1.2.3.4
      command: >
        curl -X POST -d '{"type": "pass", "interface": "{{ internet_interface }}", "ipprotocol": "inet", "protocol": "tcp", "source": "any", "sourceport": "", "destination": "1.2.3.4", "destinationport": "25", "descr": "Allow SMTP to 1.2.3.4"}, {"type": "pass", "interface": "{{ internet_interface }}", "ipprotocol": "inet", "protocol": "tcp", "source": "any", "sourceport": "", "destination": "1.2.3.4", "destinationport": "587", "descr": "Allow Submission to 1.2.3.4"}'
        http://localhost/api/v1/firewall/rules

    # Additional tasks like NAT, firewall rules, etc. can be added here
