---
- name: Configure OPNSense for KPN Fibre and IPTV
  hosts: localhost
  gather_facts: no
  vars:
    opnsense_host: "https://opnsense.localdomain"  # Replace with your OPNSense URL
    api_credentials: "{{ lookup('file', './opnsense_api_credentials.txt') }}"
    api_key: "{{ api_credentials.split()[1] }}"
    api_secret: "{{ api_credentials.split()[2] }}"
    kpn_itv_alias: "KPN_iTV_Hosts"
    #iot_net: "IoT net"

  tasks:
    - name: Configure WAN interface for KPN Fibre
      community.general.opnsense_interface:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        interface: wan
        mode: pppoe
        username: "internet"
        password: "internet"
        ipv6_type: dhcpv6
        dhcpv6_request_prefix: true
        dhcpv6_prefix_size: 48
        dhcpv6_use_ipv4: true
        apply: yes

    - name: Create VLAN 6 for internet on WAN
      community.general.opnsense_vlan:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        parent: wan
        vlan_tag: 6
        description: "KPN_INTERNET"
        apply: yes

    - name: Create VLAN 4 for IPTV on WAN
      community.general.opnsense_vlan:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        parent: wan
        vlan_tag: 4
        description: "KPN_TV"
        apply: yes

    - name: Assign VLAN 6 to WAN interface
      community.general.opnsense_interface:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        interface: vlan6
        enable: true
        description: "KPN_INTERNET"
        apply: yes

    - name: Configure KPN TV interface
      community.general.opnsense_interface:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        interface: vlan4
        enable: true
        description: "KPN_iTV"
        block_private: false
        block_bogon: false
        ipv4_type: "dhcp"
        ipv6_type: "none"
        dhcp_advanced:
          send_options: 'dhcp-class-identifier "IPTV_RG"'
          request_options: 'subnet-mask, routers, classless-routes'
        apply: yes

    - name: Enable DHCP for LAN
      community.general.opnsense_dhcp:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        interface: lan
        range_start: 192.168.2.101
        range_end: 192.168.2.199
        apply: yes

    - name: Set LAN IP address
      community.general.opnsense_interface:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        interface: lan
        ipaddr: 192.168.2.1
        subnet: 24
        apply: yes

    - name: Install IGMP Proxy
      community.general.opnsense_plugin:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        plugin: os-igmp-proxy
        state: present

    - name: Configure IGMP Proxy
      community.general.opnsense_igmp_proxy:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        upstream:
          - interface: "vlan4"
            subnet: "10.0.0.0/8, 213.75.0.0/16, 217.166.0.0/16"
        downstream:
          - interface: "lan"
            subnet: "192.168.2.0/24"
        apply: yes

    - name: Add firewall rule for DNS
      community.general.opnsense_firewall_rule:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        interface: lan
        action: pass
        protocol: udp
        source_net: "192.168.2.0/24"
        source_port: any
        destination: any
        destination_port: 53
        description: "Allow DNS"
        apply: yes

    - name: Add firewall rules for IPTV
      community.general.opnsense_firewall_rule:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        rules:
          - interface: lan
            action: pass
            protocol: igmp
            source: any
            destination: any
            description: "Allow IGMP on LAN"
          - interface: vlan4
            action: pass
            protocol: igmp
            source: "10.0.0.0/8, 213.75.0.0/16, 217.166.0.0/16"
            destination: "224.0.0.0/4"
            description: "Allow IGMP on IPTV VLAN"
          - interface: vlan4
            action: pass
            protocol: udp
            source: "10.0.0.0/8, 213.75.0.0/16, 217.166.0.0/16"
            destination: "224.0.0.0/4"
            description: "Allow UDP on IPTV VLAN"
        apply: yes

    - name: Set NAT mode to Hybrid Outbound NAT
      community.general.opnsense_command:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        command: "firewall nat set outbound mode hybrid"
        apply: yes

    - name: Configure NAT rule for KPN iTV
      community.general.opnsense_nat_outbound_rule:
        host: "{{ opnsense_host }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        interface: vlan4
        protocol: any
        source_net: "{{ iot_net }}"
        destination_net: "{{ kpn_itv_alias }}"
        target: "interface_address"
        description: "NAT rule for KPN iTV"
        apply: yes
