---
- name: Update and restart services on Linux and FreeBSD boxes
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible

  tasks:
    - name: Update packages on Red Hat-alike systems
      when: ansible_facts['os_family'] in ['RedHat', 'AlmaLinux', 'Rocky', 'OracleLinux']
      dnf:
        name: '*'
        state: latest
      register: redhat_updates

    - name: Update packages on Debian/Ubuntu-based systems
      when: ansible_facts['os_family'] == 'Debian'
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
        autoclean: yes
      register: debian_updates

    - name: Update packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name: '*'
        state: latest
      register: freebsd_updates

    - name: Display update information
      debug:
        msg: |
          Updates on {{ ansible_hostname }}:
          {% if ansible_facts['os_family'] in ['RedHat', 'AlmaLinux', 'Rocky', 'OracleLinux'] %}
            {% if redhat_updates.changed %}
            Number of updates: {{ redhat_updates.results | length }}
            Updated packages: {{ redhat_updates.results | map(attribute='name') | join(', ') }}
            {% else %}
            No updates available.
            {% endif %}
          {% elif ansible_facts['os_family'] == 'Debian' %}
            {% if debian_updates.changed %}
            Number of updates: {{ debian_updates.upgraded_packages | length }}
            Updated packages: {{ debian_updates.upgraded_packages | join(', ') }}
            {% else %}
            No updates available.
            {% endif %}
          {% elif ansible_facts['os_family'] == 'FreeBSD' %}
            {% if freebsd_updates.changed %}
            Number of updates: {{ freebsd_updates.results | length }}
            Updated packages: {{ freebsd_updates.results | map(attribute='name') | join(', ') }}
            {% else %}
            No updates available.
            {% endif %}
          {% endif %}
