---
- name: Update and restart services on Linux and FreeBSD boxes
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ansible

  tasks:
    - name: Update packages on Red Hat-alike systems
      when: ansible_facts['os_family'] in ['RedHat', 'AlmaLinux', 'Rocky', 'OracleLinux']
      dnf:
        name: '*'
        state: latest
      register: redhat_updates

    - name: Update packages on Debian/Ubuntu-based systems
      when: ansible_facts['os_family'] == 'Debian'
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
        autoclean: yes
      register: debian_updates

    - name: Update packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name: '*'
        state: latest
      register: freebsd_updates

    - name: Display update information
      debug:
        msg: |
          Updates on {{ ansible_hostname }}:
          {% if redhat_updates.changed %}
          Red Hat-alike systems:
          Number of updates: {{ redhat_updates.results | length }}
          Updated packages: {{ redhat_updates.results | map(attribute='name') | join(', ') }}
          {% endif %}

          {% if debian_updates.changed %}
          Debian/Ubuntu-based systems:
          Number of updates: {{ debian_updates.cache_update_time }}
          Updated packages: Packages were updated
          {% endif %}

          {% if freebsd_updates.changed %}
          FreeBSD:
          Number of updates: {{ freebsd_updates.results | length }}
          Updated packages: {{ freebsd_updates.results | map(attribute='name') | join(', ') }}
          {% endif %}
