---
- name: Generate API Key and Secret on OPNSense
  hosts: opnsense
  gather_facts: no
  tasks:
    - name: Ensure SSH connection is working
      command: echo "SSH connection established"

    - name: Generate API key and secret
      shell: |
        echo 'api create-key api-user' | opnsense-shell
      register: api_output

    - name: Save API key and secret to local file
      local_action:
        module: copy
        content: "{{ api_output.stdout }}"
        dest: ./api.ini
