---
- name: "Configure Pfsense/Opnsense"
  become: yes
  hosts: all
  
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11  # Adjust the path as needed
  
  tasks:
    - name: Update packages on FreeBSD
      pkgng:
        name: '*'
        state: latest

    - name: Install required packages on FreeBSD
      pkgng:
        name:
          - pfSense-pkg-zabbix-agent64
          - pfSense-pkg-zabbix-proxy64
          - pfSense-pkg-Service_Watchdog
        state: present    

    - name: Set hostname and domain on pfSense
      pfsensible.core.pfsense_setup:
        hostname: "Ikrouter"
        domain: "me.kapot"
        
    - name: Add remote_mgmt alias in pfSense with host descriptions
      pfsensible.core.pfsense_alias:
        name: remote_mgmt
        address: "1.2.3.4 5.6.7.8"
        descr: "Alias for remote management IPs"
        type: host
        detail: "akart||blaat"
        state: present

    ### WAN network
    - name: Allow HTTP in VPN
      pfsensible.core.pfsense_rule:
        name: Allow HTTP in VPN
        interface: WAN
        action: pass
        ipprotocol: inet
        protocol: tcp
        source: any
        destination: "10.0.20.10"
        destination_port: "80"
        state: present
   
    - name: Allow HTTPS in VPN
      pfsensible.core.pfsense_rule:
        name: Allow HTTPS in VPN
        interface: WAN
        action: pass
        ipprotocol: inet
        protocol: tcp
        source: any
        destination: "10.0.20.10"
        destination_port: "443"
        state: present
        
    - name: Allow RDP in for OpenVPN
      pfsensible.core.pfsense_rule:
        name: Allow RDP in for OpenVPN
        interface: WAN
        action: pass
        ipprotocol: inet
        protocol: tcp
        source: remote_mgmt
        destination: "10.0.20.10"
        destination_port: "3389"
        state: present

    - name: Allow UDP in for OpenVPN
      pfsensible.core.pfsense_rule:
        name: Allow UDP in for OpenVPN
        interface: WAN
        action: pass
        ipprotocol: inet
        protocol: udp
        source: any
        destination: any
        destination_port: "1195"
        state: present
       
       ## Allow VPN Traffic
   - name: Allow UDP in for OpenVPN
      pfsensible.core.pfsense_rule:
        name: Allow UDP in and out for OpenVPN
        interface: OpenVPN
        action: pass
        ipprotocol: inet46
        protocol: udp
        source: any
        destination: any
        destination_port: any
        state: present
