---
- name: "Configure Pfsense"
  become: yes
  hosts: all
  
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11  # Adjust the path as needed
  
  tasks:
    - name: Update packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name: '*'
        state: latest

    - name: Install required packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name:
          - pfSense-pkg-zabbix-agent64
          - pfSense-pkg-zabbix-proxy64
          - pfSense-pkg-Service_Watchdog
        state: present

    - name: Check if opnsense-version command exists
      shell: opnsense-version
      ignore_errors: yes
      register: opnsense_platform_check

    - name: Check if /etc/platform file exists (pfSense)
      stat:
        path: /etc/platform
      register: pfsense_platform_check

    - name: Print result
      debug:
        msg: "The system is running {{ 'pfSense' if pfsense_platform_check.stat.exists else 'OPNsense' if opnsense_platform_check.rc == 0 else 'Unknown' }}"

    - name: Set hostname and domain on OPNsense
      puzzle.opnsense.system_settings_general:
        hostname: "opnsense"
        domain: mycorp.com
      when: opnsense_platform_check.rc == 0

    - name: Set hostname and domain on pfSense
      pfsensible.core.pfsense_setup:
        hostname: "desired-hostname"
        domain: "desired-domain"
      when: pfsense_platform_check.stat.exists    
