---
- name: "Configure Pfsense"
  become: yes
  hosts: ip.router.snap.je

tasks:
  - name: Update packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name: '*'
        state: latest

  - name: Install required packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name:
          - package1
          - package2
          - package3
        state: present

  - name: Add firewall rule for OpenVPN on pfSense
      when: ansible_facts['os_family'] == 'FreeBSD' and ansible_distribution == 'pfSense'
      pfsense.core.pfsense_rule:
        name: 'Allow OpenVPN traffic'
        action: pass
        interface: wan
        ipprotocol: any
        protocol: any
        state: present
