---
- name: "Configure Pfsense"
  become: yes
  hosts: all
  
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11  # Adjust the path as needed
  
  tasks:
    - name: Update packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name: '*'
        state: latest

    - name: Install required packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name:
          - pfSense-pkg-zabbix-agent64
          - pfSense-pkg-zabbix-proxy64
          - pfSense-pkg-Service_Watchdog
        state: present
    
    - name: Add firewall rule for OpenVPN on pfSense
      pfsensible.core.pfsense_rule:
        name: 'Allow OpenVPN traffic'
        action: pass
        interface: wan
        ipprotocol: inet46
        protocol: any
        source: any
        destination: any
        state: present

    - name: Add firewall rule to open UDP port 1194 on WAN interface
      pfsensible.core.pfsense_rule:
        name: 'Allow UDP 1194 on WAN'
        action: pass
        interface: wan
        ipprotocol: inet
        protocol: udp
        destination_port: 1194
        state: present

    - name: Add firewall rule to open UDP port 1194 on LAN interface
      pfsensible.core.pfsense_rule:
        name: 'Allow UDP 1194 on LAN'
        action: pass
        interface: lan
        ipprotocol: inet
        protocol: udp
        destination_port: 1194
        state: present

    - name: Add firewall rule to open UDP port 1194 on WireGuard interface
      pfsensible.core.pfsense_rule:
        name: 'Allow UDP 1194 on WireGuard'
        action: pass
        interface: wireguard
        ipprotocol: inet
        protocol: udp
        destination_port: 1194
        state: present   
