---
- name: "Configure Pfsense"
  become: yes
  hosts: all
  
  tasks:
    - name: Update packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name: '*'
        state: latest

    - name: Install required packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name:
          - zabbix-agent64
          - zabbix-proxy64
          - Service_Watchdog
        state: present
    
    - name: Add firewall rule for OpenVPN on pfSense
      when: ansible_facts['os_family'] == 'FreeBSD' and ansible_distribution == 'pfSense'
      pfsensible.core.pfsense_rule:
        name: 'Allow OpenVPN traffic'
        action: pass
        interface: wan
        ipprotocol: any
        protocol: any
        state: present
