---
- name: "Configure Pfsense/Opnsense"
  become: yes
  hosts: all
  
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11  # Adjust the path as needed
  
  tasks:
    - name: Update packages on FreeBSD
      pkgng:
        name: '*'
        state: latest

    - name: Install required packages on FreeBSD
      pkgng:
        name:
          - pfSense-pkg-zabbix-agent64
          - pfSense-pkg-zabbix-proxy64
          - pfSense-pkg-Service_Watchdog
        state: present    

    - name: Set hostname and domain on pfSense
      pfsensible.core.pfsense_setup:
        hostname: "Ikrouter"
        domain: "me.kapot"
        
    - name: Add remote_mgmt alias in pfSense with host descriptions
      pfsensible.core.pfsense_alias:
        name: remote_mgmt
        address: "1.2.3.4 5.6.7.8"
        descr: "Alias for remote management IPs"
        type: host
        detail: "akart||blaat"
        state: present

 ### WAN network
    - name: Allow HTTPS/HTTPS in VPN
      pfsensible.core.pfsense_rule:
        name: Allow HTTPS/HTTPS in VPN
        interface: WAN
        action: pass
        ipprotocol: ipv4
        protocol: tcp
        source: remote_mgmt
        destination: "10.0.20.10"
        destination_port: "80 443"
        state: present
   
   
 
