---
- name: "Configure Pfsense"
  become: yes
  hosts: all
  
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11  # Adjust the path as needed
  
  tasks:
    - name: Update packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name: '*'
        state: latest

    - name: Install required packages on FreeBSD
      when: ansible_facts['os_family'] == 'FreeBSD'
      pkgng:
        name:
          - pfSense-pkg-zabbix-agent64
          - pfSense-pkg-zabbix-proxy64
          - pfSense-pkg-Service_Watchdog
        state: present
    
    - name: Add firewall rule for OpenVPN on pfSense
      pfsensible.core.pfsense_rule:
        name: 'Allow OpenVPN traffic'
        action: pass
        interface: wan
        ipprotocol: inet46
        protocol: any
        state: present

     
    - name: Add firewall rule for opt1 on pfSense
      pfsensible.core.pfsense_rule:
        name: 'Allow OpenVPN traffic'
        action: pass
        interface: opt1
        ipprotocol: inet46
        protocol: any
        state: present
